//1 Análise e Desenvolvimento de Sistemas
//2 Ciência da Computação

export const grupos = [
    { id: 1, course: 1, title: 'Desenvolvimento Web', image: 'https://i.imgur.com/sosgbXb.png', whatsappLink: 'https://chat.whatsapp.com/E1QRZ48cQ1U62ThrllpmF4'},
    { id: 2, course: 1, title: 'Programação FrontEnd', image: 'https://i.imgur.com/6QCpgi3.png', whatsappLink: 'https://chat.whatsapp.com/LNsCS8pf5TF3d56CR6nOBl'},
    { id: 3, course: 1, title: 'Arquitetura de Software', image: 'https://i.imgur.com/xGuwLwv.png', whatsappLink: 'https://chat.whatsapp.com/HvVqtjvVcYy14EvwbZs9ns'},
    { id: 4, course: 1, title: 'Segurança da Informação', image: 'https://i.imgur.com/WGYShLx.png', whatsappLink: 'https://chat.whatsapp.com/LTaeveve7JsAqNHJrkGrGq'},
    { id: 5, course: 1, title: 'Design de IHC', image: 'https://i.imgur.com/xVCaiK9.png', whatsappLink: 'https://chat.whatsapp.com/KYAWmDkKkRFC08fRgbJodP'},
    { id: 6, course: 1, title: 'Processo de Software', image: '', whatsappLink: 'https://chat.whatsapp.com/EQjSszFmyDY6CqDFT017H2'},
    { id: 7, course: 1, title: 'Introdução à Computação e Suas Aplicações', image: '', whatsappLink: 'https://chat.whatsapp.com/EBfLcyiJ17vHWgXrCuTVGN'},
    { id: 8, course: 1, title: 'Fundamentos de Banco de Dados', image: 'https://i.imgur.com/w3UfoAQ.png', whatsappLink: 'https://chat.whatsapp.com/Kr3RYjLQRFL2UlTLXkbt5I'},
    { id: 9, course: 1, title: 'Fundamentos de Redes de Computadores', image: 'https://i.imgur.com/fm68fYL.png', whatsappLink: 'https://chat.whatsapp.com/C9VSZqx8qZC2OHeWOAx3kf'},
    { id: 10, course: 1, title: 'Programação I', image: '', whatsappLink: 'https://chat.whatsapp.com/CLk9ZVTPXUsCbfOCTXnoVc'},
    { id: 11, course: 1, title: 'Laboratório I', image: '', whatsappLink: 'https://chat.whatsapp.com/DAT7oTQivgr4Z0VKe2Mc3w'},
    { id: 12, course: 1, title: 'Governança em TI', image: '', whatsappLink: 'https://chat.whatsapp.com/LAGxaUzYPwU65JBPrl4z7y'},
    { id: 13, course: 1, title: 'Arquitetura da Informação', image: '', whatsappLink: 'https://chat.whatsapp.com/LwTq2bt3HrH6HsGRghvwSy'},
    { id: 14, course: 1, title: 'Ciência de dados e big data', image: '', whatsappLink: 'https://chat.whatsapp.com/LdQtd6kYV3uHJMw1uJUx8z'},
    { id: 15, course: 1, title: 'Engenharia de Software: Projeto', image: '', whatsappLink: 'https://chat.whatsapp.com/GuCGgkEjtKDAlcDMxuoVfD'},
    { id: 16, course: 1, title: 'Gestão Inf. Conhecimento', image: '', whatsappLink: 'https://chat.whatsapp.com/JVUVatsa2JSALtUWcOUXic'},
    { id: 17, course: 1, title: 'Sistemas Integrados', image: '', whatsappLink: 'https://chat.whatsapp.com/Gz3paOVbZTJCiYP7vJ4pYO'},
    { id: 18, course: 1, title: 'Aval/Sel - Solu Tec e ROI', image: '', whatsappLink: 'https://chat.whatsapp.com/Kf3wSHgsivc1R1yDedeowi'},
    { id: 19, course: 1, title: 'Gestão de Sistemas de Informação', image: 'https://i.imgur.com/s9dnY9N.png', whatsappLink: 'https://chat.whatsapp.com/L0SjUzH7MdaHzMQ0Hqvv7Y'},
    { id: 20, course: 1, title: 'Gerência da Configuração de Software', image: 'https://i.imgur.com/l2Ui1rr.png', whatsappLink: 'https://chat.whatsapp.com/D4HK2HICzzG3Kr37Ci6iR9'},
    { id: 21, course: 1, title: 'Cálculo Diferencial', image: 'https://i.imgur.com/t7xyXDy.png', whatsappLink: 'https://chat.whatsapp.com/LEhtY60hcju69BIRfXWevx'},
    { id: 22, course: 1, title: 'Projeto de Sistemas Digitais', image: 'https://i.imgur.com/N9hQVVu.png', whatsappLink: 'https://chat.whatsapp.com/FP3Js5u74gV8wpqra5ttnj'},
    { id: 23, course: 1, title: 'Métricas e gerência de projetos', image: 'https://i.imgur.com/EjS6aBn.png', whatsappLink: 'https://chat.whatsapp.com/JE2NtHtoEzfF9IuFYe2wr7'},
    { id: 24, course: 1, title: 'Programação para Dispositivos Móveis', image: 'https://i.imgur.com/7ukXiZK.png', whatsappLink: 'https://chat.whatsapp.com/KGtK9Iih2YZIsPJK5jQJKB'},
    { id: 25, course: 1, title: 'Processos de Teste de Software', image: 'https://i.imgur.com/NBOBiCR.png', whatsappLink: 'https://chat.whatsapp.com/JvfRlKdBEQQLPZuTvBOWDn'},
    { id: 26, course: 1, title: 'Logística e Distribuição', image: '', whatsappLink: 'https://chat.whatsapp.com/J8AcbRTd0a85PkWnjVCKSi'},
    { id: 27, course: 1, title: 'Melhoria de Processo de Software', image: 'https://i.imgur.com/ojvdDCW.png', whatsappLink: 'https://chat.whatsapp.com/Cn6W9sv6ypWCgpcKI19nbD'},
    { id: 28, course: 1, title: 'Programação II', image: '', whatsappLink: 'https://chat.whatsapp.com/L79kkc6R3sZ0bSGhzZxmmU'},
    { id: 29, course: 1, title: 'Engenharia de Software: Análise', image: '', whatsappLink: 'https://chat.whatsapp.com/CkpE62gDba8LjIqX9tB7i8'},
    { id: 30, course: 1, title: 'Laboratório II', image: '', whatsappLink: 'https://chat.whatsapp.com/I3jNvxdI4R7JMmJ3oXdlJp'},
    { id: 31, course: 1, title: 'Gestão por Processos', image: '', whatsappLink: 'https://chat.whatsapp.com/KbQY6IfHxbB1yYbJT7aPel'},
    { id: 32, course: 1, title: 'Negociação Empresarial', image: '', whatsappLink: 'https://chat.whatsapp.com/EzFxft7vd1JGQn5nlOH9Mu'},
    { id: 33, course: 1, title: 'Modelagem e Otimização', image: '', whatsappLink: 'https://chat.whatsapp.com/FUmZ551QESX1jX1Jss38Ko'},
    { id: 34, course: 1, title: 'Fundamentos de Marketing', image: '', whatsappLink: 'https://chat.whatsapp.com/IsGgBNRx6dKISKS5tYtAE0'},
    { id: 35, course: 1, title: 'Direito de Empresas e Negócios', image: '', whatsappLink: 'https://chat.whatsapp.com/HrRu1MluN173BginCbQy2t'},
    { id: 36, course: 1, title: 'Administração Estratégica I', image: '', whatsappLink: 'https://chat.whatsapp.com/FBK3t993rxp92nQMmNtz3w'},
    { id: 37, course: 1, title: 'Gestão e Garantia da Qualidade de Processos', image: '', whatsappLink: 'https://chat.whatsapp.com/EYVmQOxPoWjIpWBVAQHWWN'},
    { id: 38, course: 1, title: 'Empreendedorismo e Souções de Problemas', image: '', whatsappLink: 'https://chat.whatsapp.com/JEtoR5G6m2VBu95S0Hbyz6'},
    { id: 39, course: 1, title: 'Temas Emergentes Gest. TI', image: '', whatsappLink: 'https://chat.whatsapp.com/KHrT5HMmc5wJKuVz9u6mRw'},
    { id: 40, course: 1, title: 'Gerência de Projeto de Software', image: '', whatsappLink: 'https://chat.whatsapp.com/CfRFUsB4JhHC9z7lCouYzg'},
    { id: 41, course: 1, title: 'Engenharia de Software - Requisitos', image: '', whatsappLink: 'https://chat.whatsapp.com/BwxnmHQv4k5ErV8wOXHBNA'},
    { id: 42, course: 1, title: 'Fundamentos de Sistemas Operacionais', image: '', whatsappLink: 'https://chat.whatsapp.com/KRoL0FFulE1CnkPFGejs8c'},
    { id: 43, course: 1, title: 'Tecnocultura', image: '', whatsappLink: 'https://chat.whatsapp.com/Gd8l8u8hTIr1rZ6wU3WPaQ'},
    { id: 44, course: 1, title: 'Projeto Final I', image: 'https://i.imgur.com/DULe9uI.png', whatsappLink: 'https://chat.whatsapp.com/Lhk3G6AxRMD0Wayi4vWDeU'},
    { id: 45, course: 1, title: 'Projeto Final II', image: 'https://i.imgur.com/M1J5vtX.png', whatsappLink: 'https://chat.whatsapp.com/HhQJjftPEdV71nWXeayRfh'},
    { id: 46, course: 1, title: 'Raciocínio Lógico', image: '', whatsappLink: 'https://chat.whatsapp.com/BpRTMHJa6RpHIhjdcss3ZN'},
    { id: 47, course: 1, title: 'Matemática para Computação', image: '', whatsappLink: 'https://chat.whatsapp.com/JWZMpVHiIIM4aauTmBue3X'},
    { id: 48, course: 1, title: 'Comércio Eletrônico', image: '', whatsappLink: 'https://chat.whatsapp.com/G4xlPUs6urY6IsakFzBFQ7'},
    { id: 49, course: 1, title: 'Relacionamento e Marketing Virtual', image: '', whatsappLink: 'https://chat.whatsapp.com/LNnQkygixWMCGU97cAZdVL'},
    { id: 50, course: 1, title: 'Inovação Social', image: '', whatsappLink: 'https://chat.whatsapp.com/C2EP5a0OoZX3gFf9vVmaKv'},
    { id: 51, course: 1, title: 'América Latina Desenvolvimento e Sustentabilidade', image: '', whatsappLink: 'https://chat.whatsapp.com/HO3IFWJCzX14lhyt3RwJf9'},

    { id: 52, course: 2, title: 'Cálculo Diferencial', image: 'https://i.imgur.com/t7xyXDy.png', whatsappLink: 'https://chat.whatsapp.com/LEhtY60hcju69BIRfXWevx'},
    { id: 53, course: 2, title: 'Segurança da Informação', image: 'https://i.imgur.com/WGYShLx.png', whatsappLink: 'https://chat.whatsapp.com/LTaeveve7JsAqNHJrkGrGq'},
    
]
